-- =====================================================================
-- V1: Initial schema
-- ---------------------------------------------------------------------
-- Creates the tables, indexes and constraints for the food ordering and
-- delivery platform. The DDL mirrors the JPA entities in the 'common'
-- module so that spring.jpa.hibernate.ddl-auto=validate passes.
-- =====================================================================

-- ---------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------
CREATE TABLE users (
    id          UUID         NOT NULL,
    name        VARCHAR(100) NOT NULL,
    phone       VARCHAR(20)  NOT NULL,
    role        VARCHAR(255) NOT NULL,
    banned      BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL,
    created_by  UUID,
    updated_at  TIMESTAMPTZ  NOT NULL,
    updated_by  UUID,
    deleted_at  TIMESTAMPTZ,
    deleted_by  UUID,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_phone UNIQUE (phone)
);

CREATE INDEX idx_users_banned ON users (banned);

-- ---------------------------------------------------------------------
-- owners
-- ---------------------------------------------------------------------
CREATE TABLE owners (
    id          UUID        NOT NULL,
    user_id     UUID        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL,
    created_by  UUID,
    updated_at  TIMESTAMPTZ NOT NULL,
    updated_by  UUID,
    deleted_at  TIMESTAMPTZ,
    deleted_by  UUID,
    CONSTRAINT pk_owners PRIMARY KEY (id),
    CONSTRAINT fk_owners_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uq_owners_user UNIQUE (user_id)
);

CREATE INDEX idx_owners_user ON owners (user_id);

-- ---------------------------------------------------------------------
-- shippers
-- ---------------------------------------------------------------------
CREATE TABLE shippers (
    id          UUID        NOT NULL,
    user_id     UUID        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL,
    created_by  UUID,
    updated_at  TIMESTAMPTZ NOT NULL,
    updated_by  UUID,
    deleted_at  TIMESTAMPTZ,
    deleted_by  UUID,
    CONSTRAINT pk_shippers PRIMARY KEY (id),
    CONSTRAINT fk_shippers_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uq_shippers_user UNIQUE (user_id)
);

CREATE INDEX idx_shippers_user ON shippers (user_id);

-- ---------------------------------------------------------------------
-- restaurants
-- ---------------------------------------------------------------------
CREATE TABLE restaurants (
    id          UUID          NOT NULL,
    owner_id    UUID          NOT NULL,
    name        VARCHAR(150)  NOT NULL,
    phone       VARCHAR(20)   NOT NULL,
    description VARCHAR(300)  NOT NULL,
    address     VARCHAR(100)  NOT NULL,
    district    VARCHAR(100)  NOT NULL,
    city        VARCHAR(100)  NOT NULL,
    latitude    NUMERIC(9, 6) NOT NULL,
    longitude   NUMERIC(9, 6) NOT NULL,
    open_hour   TIME          NOT NULL,
    close_hour  TIME          NOT NULL,
    status      VARCHAR(20)   NOT NULL,
    created_at  TIMESTAMPTZ   NOT NULL,
    created_by  UUID,
    updated_at  TIMESTAMPTZ   NOT NULL,
    updated_by  UUID,
    deleted_at  TIMESTAMPTZ,
    deleted_by  UUID,
    CONSTRAINT pk_restaurants PRIMARY KEY (id),
    CONSTRAINT fk_restaurants_owner FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT uq_restaurants_phone UNIQUE (phone)
);

CREATE INDEX idx_restaurants_owner ON restaurants (owner_id);
CREATE INDEX idx_restaurants_status ON restaurants (status);
CREATE INDEX idx_restaurants_location ON restaurants (latitude, longitude);

-- ---------------------------------------------------------------------
-- restaurant_sections
-- ---------------------------------------------------------------------
CREATE TABLE restaurant_sections (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    restaurant_id UUID         NOT NULL,
    name          VARCHAR(100) NOT NULL,
    display_order      BIGINT       NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL,
    created_by    UUID,
    updated_at    TIMESTAMPTZ  NOT NULL,
    updated_by    UUID,
    deleted_at    TIMESTAMPTZ,
    deleted_by    UUID,
    CONSTRAINT pk_restaurant_sections PRIMARY KEY (id),
    CONSTRAINT fk_sections_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants (id),
    CONSTRAINT uq_section_restaurant_name UNIQUE (restaurant_id, name)
);

CREATE INDEX idx_sections_restaurant ON restaurant_sections (restaurant_id);

-- ---------------------------------------------------------------------
-- menu_items
-- ---------------------------------------------------------------------
CREATE TABLE menu_items (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    restaurant_id         UUID           NOT NULL,
    restaurant_section_id BIGINT         NOT NULL,
    name                  VARCHAR(200)   NOT NULL,
    image                 VARCHAR(500),
    price                 NUMERIC(12, 2) NOT NULL,
    discount_rate         NUMERIC(5, 2),
    display_order              BIGINT         NOT NULL,
    status                VARCHAR(20)    NOT NULL,
    version               BIGINT         NOT NULL,
    created_at            TIMESTAMPTZ    NOT NULL,
    created_by            UUID,
    updated_at            TIMESTAMPTZ    NOT NULL,
    updated_by            UUID,
    deleted_at            TIMESTAMPTZ,
    deleted_by            UUID,
    CONSTRAINT pk_menu_items PRIMARY KEY (id),
    CONSTRAINT fk_menu_items_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants (id),
    CONSTRAINT fk_menu_items_section FOREIGN KEY (restaurant_section_id) REFERENCES restaurant_sections (id)
);

CREATE INDEX idx_menu_items_restaurant ON menu_items (restaurant_id);
CREATE INDEX idx_menu_items_section ON menu_items (restaurant_section_id);
CREATE INDEX idx_menu_items_restaurant_status ON menu_items (restaurant_id, status);
-- ---------------------------------------------------------------------
-- deliveries
-- ---------------------------------------------------------------------
CREATE TABLE deliveries (
    id                 UUID           NOT NULL,
    code               VARCHAR(30)    NOT NULL,
    user_id            UUID           NOT NULL,
    status             VARCHAR(30)    NOT NULL,
    subtotal           NUMERIC(12, 2) NOT NULL,
    discounted_amount    NUMERIC(12, 2) NOT NULL,
    shipping_fee       NUMERIC(12, 2) NOT NULL,
    total_amount       NUMERIC(12, 2) NOT NULL,
    distance           NUMERIC(10, 2),
    shipper_revenue    NUMERIC(12, 2),
    expected_delivery_at TIMESTAMPTZ,
    delivered_at       TIMESTAMPTZ,
    created_at         TIMESTAMPTZ    NOT NULL,
    created_by         UUID,
    updated_at         TIMESTAMPTZ    NOT NULL,
    updated_by         UUID,
    deleted_at         TIMESTAMPTZ,
    deleted_by         UUID,
    CONSTRAINT pk_deliveries PRIMARY KEY (id),
    CONSTRAINT fk_deliveries_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uq_deliveries_code UNIQUE (code)
);

CREATE INDEX idx_deliveries_user ON deliveries (user_id);
CREATE INDEX idx_deliveries_status ON deliveries (status);
CREATE INDEX idx_deliveries_user_status ON deliveries (user_id, status);
CREATE INDEX idx_deliveries_expected_delivery ON deliveries (expected_delivery_at);

-- ---------------------------------------------------------------------
-- delivery_items
-- ---------------------------------------------------------------------
CREATE TABLE delivery_items (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    delivery_id      UUID           NOT NULL,
    menu_item_id     BIGINT,
    item_name        VARCHAR(200)   NOT NULL,
    unit_price            NUMERIC(12, 2) NOT NULL,
    line_total            NUMERIC(12, 2) NOT NULL,
    discount_rate    NUMERIC(5, 2),
    quantity           INTEGER        NOT NULL,
    created_at       TIMESTAMPTZ    NOT NULL,
    created_by       UUID,
    updated_at       TIMESTAMPTZ    NOT NULL,
    updated_by       UUID,
    deleted_at       TIMESTAMPTZ,
    deleted_by       UUID,
    CONSTRAINT pk_delivery_items PRIMARY KEY (id),
    CONSTRAINT fk_delivery_items_delivery FOREIGN KEY (delivery_id) REFERENCES deliveries (id),
    CONSTRAINT fk_delivery_items_menu_item FOREIGN KEY (menu_item_id) REFERENCES menu_items (id)
);

CREATE INDEX idx_delivery_items_delivery ON delivery_items (delivery_id);
CREATE INDEX idx_delivery_items_menu_item ON delivery_items (menu_item_id);
-- ---------------------------------------------------------------------
-- delivery_assignments
-- ---------------------------------------------------------------------
CREATE TABLE delivery_assignments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    delivery_id     UUID        NOT NULL,
    shipper_id      UUID        NOT NULL,
    sequence_number INTEGER,
    status          VARCHAR(30) NOT NULL,
    expires_at      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL,
    created_by      UUID,
    updated_at      TIMESTAMPTZ NOT NULL,
    updated_by      UUID,
    deleted_at      TIMESTAMPTZ,
    deleted_by      UUID,
    CONSTRAINT pk_delivery_assignments PRIMARY KEY (id),
    CONSTRAINT fk_assignments_delivery FOREIGN KEY (delivery_id) REFERENCES deliveries (id),
    CONSTRAINT fk_assignments_shipper FOREIGN KEY (shipper_id) REFERENCES shippers (id)
);

CREATE INDEX idx_assignments_shipper_status ON delivery_assignments (shipper_id, status);
CREATE INDEX idx_assignments_delivery_sequence ON delivery_assignments (delivery_id, sequence_number);
CREATE INDEX idx_assignments_expiration ON delivery_assignments (expires_at);

-- ---------------------------------------------------------------------
-- otp
-- ---------------------------------------------------------------------
CREATE TABLE otp (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    phone      VARCHAR(255),
    otp        VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL,
    created_by UUID,
    updated_at TIMESTAMPTZ NOT NULL,
    updated_by UUID,
    deleted_at TIMESTAMPTZ,
    deleted_by UUID,
    CONSTRAINT pk_otp PRIMARY KEY (id)
);

CREATE INDEX idx_otp ON otp (otp);
